source 'https://rubygems.org'

# Specify your gem's dependencies in drg.gemspec
gemspec
# gem 'duck_puncher'
gem 'usable'
group :development, :test do
  # gem 'rubocop', '~> 0.29', require: false
  gem "pry", '~> 0.10'
  gem 'object_tracker', '>= 1.0.5'
  gem 'byebug', '~> 1.2', :require => false
  gem 'rack-cache', '~> 1.2', :require => 'rack/cache'
end
gem 'ruby_parser', '3.7.1'
gem 'aws-sdk',                  '>= 1.56.0'   # Amazon Web Services
gem 'whenever',                 require: false
gem 'duck_puncher', '> 1', '< 2'
gem 'slop'